/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTBitwiseXorNode extends ExpressionNode
{
  public ASTBitwiseXorNode(int id)
  {
    super(id);
  }
  
  public ASTBitwiseXorNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
