/* Generated By:JJTree: Do not edit this line. ASTFunctionNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTFunctionNode extends ExpressionNode
{
  
  public String name;
  
  public ASTFunctionNode(int id)
  {
    super(id);
  }
  
  public ASTFunctionNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
