/* Generated By:JJTree: Do not edit this line. ASTFloatConstNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTFloatConstNode extends ExpressionNode
{
  public Float floatVal;
  public Double doubleVal;
  
  public ASTFloatConstNode(int id)
  {
    super(id);
  }
  
  public ASTFloatConstNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  @Override
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
