/* Generated By:JJTree: Do not edit this line. ASTLongConstNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTLongConstNode extends ExpressionNode
{
  public long val;
  
  public ASTLongConstNode(int id)
  {
    super(id);
  }
  
  public ASTLongConstNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
