/* Generated By:JJTree: Do not edit this line. ASTLeftShiftNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tibbo.aggregate.common.expression.parser;

public
class ASTLeftShiftNode extends ExpressionNode {
  public ASTLeftShiftNode(int id) {
    super(id);
  }

  public ASTLeftShiftNode(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.tibbo.aggregate.common.expression.AttributedObject jjtAccept(ExpressionParserVisitor visitor, com.tibbo.aggregate.common.expression.EvaluationEnvironment data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c2c617c240f7915afc2af5ef4b46ac2 (do not edit this line) */
