/* Generated By:JJTree: Do not edit this line. ASTRightShiftNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tibbo.aggregate.common.expression.parser;

public
class ASTRightShiftNode extends ExpressionNode {
  public ASTRightShiftNode(int id) {
    super(id);
  }

  public ASTRightShiftNode(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public com.tibbo.aggregate.common.expression.AttributedObject jjtAccept(ExpressionParserVisitor visitor, com.tibbo.aggregate.common.expression.EvaluationEnvironment data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57fc6d573f12b85978eb3d21fc46fe87 (do not edit this line) */
