/* Generated By:JJTree: Do not edit this line. ASTStringConstNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTStringConstNode extends ExpressionNode
{
  public String val;
  
  public ASTStringConstNode(int id)
  {
    super(id);
  }
  
  public ASTStringConstNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
