/* Generated By:JJTree: Do not edit this line. ASTUnaryNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTUnaryNode extends ExpressionNode
{
  public ASTUnaryNode(int id)
  {
    super(id);
  }
  
  public ASTUnaryNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
