/* Generated By:JJTree: Do not edit this line. ASTValueReferenceNode.java */

package com.tibbo.aggregate.common.expression.parser;

import com.tibbo.aggregate.common.expression.*;

public class ASTValueReferenceNode extends ExpressionNode
{
  public String uriImage;
  
  public Reference reference;
  
  public ASTValueReferenceNode(int id)
  {
    super(id);
  }
  
  public ASTValueReferenceNode(ExpressionParser p, int id)
  {
    super(p, id);
  }
  
  /** Accept the visitor. **/
  @Override
  public AttributedObject jjtAccept(ExpressionParserVisitor visitor, EvaluationEnvironment data)
  {
    return visitor.visit(this, data);
  }
}
