/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package com.tibbo.aggregate.common.expression.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTCONDITIONALNODE = 2;
  public int JJTLOGICALORNODE = 3;
  public int JJTLOGICALANDNODE = 4;
  public int JJTBITWISEORNODE = 5;
  public int JJTBITWISEXORNODE = 6;
  public int JJTBITWISEANDNODE = 7;
  public int JJTEQNODE = 8;
  public int JJTNENODE = 9;
  public int JJTREGEXMATCHNODE = 10;
  public int JJTLTNODE = 11;
  public int JJTGTNODE = 12;
  public int JJTLENODE = 13;
  public int JJTGENODE = 14;
  public int JJTRIGHTSHIFTNODE = 15;
  public int JJTUNSIGNEDRIGHTSHIFTNODE = 16;
  public int JJTLEFTSHIFTNODE = 17;
  public int JJTADDNODE = 18;
  public int JJTSUBTRACTNODE = 19;
  public int JJTMULNODE = 20;
  public int JJTDIVNODE = 21;
  public int JJTMODNODE = 22;
  public int JJTUNARYNODE = 23;
  public int JJTLOGICALNOTNODE = 24;
  public int JJTBITWISENOTNODE = 25;
  public int JJTFUNCTIONNODE = 26;
  public int JJTVALUEREFERENCENODE = 27;
  public int JJTLONGCONSTNODE = 28;
  public int JJTFLOATCONSTNODE = 29;
  public int JJTSTRINGCONSTNODE = 30;
  public int JJTNULLNODE = 31;
  public int JJTTRUENODE = 32;
  public int JJTFALSENODE = 33;


  public String[] jjtNodeName = {
    "void",
    "Start",
    "ConditionalNode",
    "LogicalOrNode",
    "LogicalAndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "RegexMatchNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "RightShiftNode",
    "UnsignedRightShiftNode",
    "LeftShiftNode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryNode",
    "LogicalNotNode",
    "BitwiseNotNode",
    "FunctionNode",
    "ValueReferenceNode",
    "LongConstNode",
    "FloatConstNode",
    "StringConstNode",
    "NullNode",
    "TrueNode",
    "FalseNode",
  };
}
/* JavaCC - OriginalChecksum=0f80b9e7f3b0aef146141b0a94627608 (do not edit this line) */
