/* Generated By:JavaCC: Do not edit this line. ExpressionParserVisitor.java Version 5.0 */
package com.tibbo.aggregate.common.expression.parser;

public interface ExpressionParserVisitor
{
  public com.tibbo.aggregate.common.expression.AttributedObject visit(SimpleNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTStart node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTConditionalNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLogicalOrNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLogicalAndNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTBitwiseOrNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTBitwiseXorNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTBitwiseAndNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTEQNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTNENode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTRegexMatchNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLTNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTGTNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLENode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTGENode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTRightShiftNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTUnsignedRightShiftNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLeftShiftNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTAddNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTSubtractNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTMulNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTDivNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTModNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTUnaryNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLogicalNotNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTBitwiseNotNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTFunctionNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTValueReferenceNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTLongConstNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTFloatConstNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTStringConstNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTNullNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTTrueNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
  public com.tibbo.aggregate.common.expression.AttributedObject visit(ASTFalseNode node, com.tibbo.aggregate.common.expression.EvaluationEnvironment data);
}
/* JavaCC - OriginalChecksum=15fb91688def7a1546f918758ad53148 (do not edit this line) */
